---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1grehj0ezmvezy83x8sxeewknqcw66g5ct544mdh4wl64j83hc98sv4h5w4"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1grehj0ezmvezy83x8sxeewknqcw66g5ct544mdh4wl64j83hc98sv4h5w4"
  # https://github.com/ansible-collections/community.sops/issues/153
  - path_regex: /dev/stdin
    key_groups:
      - age:
          - "age1grehj0ezmvezy83x8sxeewknqcw66g5ct544mdh4wl64j83hc98sv4h5w4"
