apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:LpCKGh9FiQv6VzTHTy+cQO5S+PyQ6cX9,iv:INHTqkDCOmS1CpAZJpac15KP6fSj4fXJsHfkE2eUO4g=,tag:a0ClnnZomJATbJbm9Jvtbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grehj0ezmvezy83x8sxeewknqcw66g5ct544mdh4wl64j83hc98sv4h5w4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdlVsUGQwMWk4NGVNWS8w
            K092SGNiQWpxZXViZDB3MUtrTEZJQVFYcldNCmpRbFBlVG9DNlhNQjJ3L0tOT0RU
            S0NSb3VzL3JHdXVjL1pJa2xQd1lsWGsKLS0tIGdZSmN3eGM5MDI1aFZDb1NrN3lv
            VjM2YUZwK0kya0tuMEdla3FyRGxRTUUKZxLdFsmdQNwpCafA34sSB0ql9zbNs7KW
            CAQvHaxpFltU8IYlqODuFVDTRsOMnzuHEHmaFuYQo0RT6Y29dWco8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T20:34:56Z"
    mac: ENC[AES256_GCM,data:hjg7XmYl41X6wQ9WMN4r4AmNWQihV4k2iMJAZr7o4Ko7QtDCHNW5SYYFszjuscrfD1DjSrkwl18v8hs7pFy65cR9MZFIpMSUnYm6wNBNx9y4Nq0KQwmiqIcHAkEFNg3yQUPBSpAjyLlekShbuwdPnkhcn9hk1G0asFDcHwnET5g=,iv:zd74Jtswl1eXG1gIBPnARtVEDNaDcFa2m6fToVHVqd0=,tag:2Os/y+EyjNCdOHAqkbX+hQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
