apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4ncLL9BT+4tsaje6bLHOzRwgJuXXLdAbnwaV5zBw9rQIWxXe8BzrCw==,iv:BdK+L6fIZumg7cteRQEkaiZ+NlPu6nrSIpufGXAmC4o=,tag:4OtbFivRQtb1nxbTHEyY5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grehj0ezmvezy83x8sxeewknqcw66g5ct544mdh4wl64j83hc98sv4h5w4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNjlhV25rVzg0MzlSblFR
            VHBqWmVMdTlLaVNTbW9BNUpUYWhSYTREbXo4CnZ0dURwR0lhdFBXU1RtYzkrMjdK
            RGk3RkZsb1FuOWd3SlVIMkQvVHFNclUKLS0tIEJJZ0pKTWp0U3BSSDNyaDB2cTl2
            eHhNbnMxZURrMEExVjRhakFnQVBTdkkKt9xpf5c8vN5hqUMZmjijmsciQda/kPVm
            BXOltCsZSN9AUkn96bWPYYWKJiMth6ftZw9F4GtE08j6iCs+fAmU0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T20:34:56Z"
    mac: ENC[AES256_GCM,data:ANd3dW0yu52zTdYyP4SLnvPv8qrRpwhNo5CHRk+jA+FLhMBnTrHElMYMD7k7s5xw0DyyRAcLxNQsSA8Ql5LE6oyZQ7//k1LfNoGg1E8CfA/Dp+5nmhcMreFJ3eHMUv7snjg25o4No2OFwPEutguxuBaO6fljsIElKILvZppPlLI=,iv:vNdbGvJWPI6fPIEGpDhoLyQ+Ke1bWVBGh+KEG7Pv4XQ=,tag:Vm0YSkiCh8Qnh2ryGZfocg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
