---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    timeout: 10m
    remediation:
      retries: 3

  values:
    podDefaultOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        containers:

          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2023.12.3
            env:
              TZ: America/Los_Angeles
              HASS_TRUSTED_PROXIES: ${CONFIG_CLUSTER_PODS_NETWORK_IP_POOL}

            initContainers:
              init:
                image:
                  repository: busybox
                  tag: "1.36.1"
                command:
                  - "/bin/sh"
                args:
                  - "/init.sh"

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 750Mi

          code:
            dependsOn: main
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.19.1
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - --port
              - "8081"
              - "/config"

    configMaps:
      scripts:
        enabled: true
        data:
          init.sh: |
            #!/bin/sh
            echo "run $0"
            cp -nv /init/* /config/

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-pv
        mountPath: /home-assistant

    service:
      main:
        ports:
          http:
            port: &port 8123

      code:
        controller: main
        ports:
          http:
            port: &codeport 8081

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:home-assistant
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port
                  name: main
        tls:
          - hosts:
              - *host

      code:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:home-assistant
        hosts:
          - host: &codehost "hass-config.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *codeport
                  name: code
        tls:
          - hosts:
              - *codehost
