---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: home-assistant-init
    files:
      - init/confiugration.yaml
generatorOptions:
  disableNameSuffixHash: True
