---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pv
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
