---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pv
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-provision
