---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pv
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
